In [1]:
import sys

print(sys.executable)

c:\Nifty100_Data_Foundation\.venv\Scripts\python.exe

In [2]:
print("="*60)
print("NIFTY100 FINANCIAL DATA PLATFORM")
print("Sprint 1 : Day 01")
print("Environment Setup & Dataset Exploration")
print("="*60)

============================================================
NIFTY100 FINANCIAL DATA PLATFORM
Sprint 1 : Day 01
Environment Setup & Dataset Exploration
============================================================

In [3]:
import os
from pathlib import Path

import pandas as pd
import numpy as np

from IPython.display import display

In [5]:
PROJECT_ROOT = Path.cwd().parent
RAW_DATA = PROJECT_ROOT /"data"/"raw"
PROCESSED_DATA=PROJECT_ROOT/"data"/"processed"
OUTPUT_DIR =PROJECT_ROOT/"data"/"output"

print("Project Root :", PROJECT_ROOT)
print("Raw Data     :", RAW_DATA)
print("Processed    :", PROCESSED_DATA)
print("Output       :", OUTPUT_DIR)

Project Root : c:\Nifty100_Data_Foundation
Raw Data     : c:\Nifty100_Data_Foundation\data\raw
Processed    : c:\Nifty100_Data_Foundation\data\processed
Output       : c:\Nifty100_Data_Foundation\data\output

In [6]:
excel_files= sorted(RAW_DATA.glob("*.xlsx"))
print(f"found {len(excel_files)} Excel Files\n")
for file in excel_files:
    print(file.name)

found 12 Excel Files

analysis.xlsx
balancesheet.xlsx
cashflow.xlsx
companies.xlsx
documents.xlsx
financial_ratios.xlsx
market_cap.xlsx
peer_groups.xlsx
profitandloss.xlsx
prosandcons.xlsx
sectors.xlsx
stock_prices.xlsx

In [7]:
summary=[]
for files in excel_files:
    xls= pd.ExcelFile(files)
    summary.append({
        "File Name": files.name,
        "Sheet Names": ", ".join(xls.sheet_names),
        "Number of Sheets": len(xls.sheet_names)
    })
summary=pd.DataFrame(summary)
display(summary)

                File Name    Sheet Names  Number of Sheets
0           analysis.xlsx       Analysis                 1
1       balancesheet.xlsx  Balance Sheet                 1
2           cashflow.xlsx      Cash Flow                 1
3          companies.xlsx      Companies                 1
4          documents.xlsx      Documents                 1
5   financial_ratios.xlsx         Sheet1                 1
6         market_cap.xlsx         Sheet1                 1
7        peer_groups.xlsx         Sheet1                 1
8      profitandloss.xlsx  Profit & Loss                 1
9        prosandcons.xlsx    Pros & Cons                 1
10           sectors.xlsx         Sheet1                 1
11      stock_prices.xlsx         Sheet1                 1

In [8]:
dataset_summary = []

for file in excel_files:

    df = pd.read_excel(file)

    dataset_summary.append({
        "Dataset": file.stem,
        "Rows": df.shape[0],
        "Columns": df.shape[1]
    })

dataset_summary = pd.DataFrame(dataset_summary)

display(dataset_summary)

             Dataset  Rows  Columns
0           analysis    21        6
1       balancesheet  1313       13
2           cashflow  1188        7
3          companies    93       12
4          documents  1586        4
5   financial_ratios  1184       16
6         market_cap   552        9
7        peer_groups    56        4
8      profitandloss  1277       15
9        prosandcons    17        4
10           sectors    92        6
11      stock_prices  5520        9

In [9]:
for file in excel_files:

    print("="*70)
    print(file.stem.upper())
    print("="*70)

    df = pd.read_excel(file)

    print(df.columns.tolist())

    print()

======================================================================
ANALYSIS
======================================================================
['Bluestock Fintech — Nifty 100  |  Analysis  |  20 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5']

======================================================================
BALANCESHEET
======================================================================
['Bluestock Fintech — Nifty 100  |  Balance Sheet  |  1,312 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

======================================================================
CASHFLOW
======================================================================
['Bluestock Fintech — Nifty 100  |  Cash Flow  |  1,187 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6']

======================================================================
COMPANIES
======================================================================
['Mkt Fintech — Nifty 100  |  Companies  |  92 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11']

======================================================================
DOCUMENTS
======================================================================
['Bluestock Fintech — Nifty 100  |  Documents  |  1,585 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

======================================================================
FINANCIAL_RATIOS
======================================================================
['id', 'company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr']

======================================================================
MARKET_CAP
======================================================================
['id', 'company_id', 'year', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct']

======================================================================
PEER_GROUPS
======================================================================
['id', 'peer_group_name', 'company_id', 'is_benchmark']

======================================================================
PROFITANDLOSS
======================================================================
['Bluestock Fintech — Nifty 100  |  Profit & Loss  |  1,276 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']

======================================================================
PROSANDCONS
======================================================================
['Bluestock Fintech — Nifty 100  |  Pros & Cons  |  16 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3']

======================================================================
SECTORS
======================================================================
['id', 'company_id', 'broad_sector', 'sub_sector', 'index_weight_pct', 'market_cap_category']

======================================================================
STOCK_PRICES
======================================================================
['id', 'company_id', 'date', 'open_price', 'high_price', 'low_price', 'close_price', 'volume', 'adjusted_close']

In [10]:
missing_summary = []

for file in excel_files:

    df = pd.read_excel(file)

    missing_summary.append({
        "Dataset": file.stem,
        "Missing Values": int(df.isna().sum().sum())
    })

missing_summary = pd.DataFrame(missing_summary)

display(missing_summary)

             Dataset  Missing Values
0           analysis               0
1       balancesheet               0
2           cashflow               8
3          companies               9
4          documents              52
5   financial_ratios             170
6         market_cap               0
7        peer_groups               0
8      profitandloss             231
9        prosandcons               6
10           sectors               0
11      stock_prices               0

In [11]:
dataset_summary.to_csv(
    OUTPUT_DIR / "dataset_summary.csv",
    index=False
)

missing_summary.to_csv(
    OUTPUT_DIR / "missing_summary.csv",
    index=False
)

print("Dataset summary saved successfully.")

Dataset summary saved successfully.