In [1]:
import pandas as pd
from pathlib import Path
from IPython.display import display

In [2]:
PROJECT_ROOT = Path.cwd().parent
RAW_DATA= PROJECT_ROOT/"data"/"raw"
excel_files = sorted(RAW_DATA.glob("*.xlsx"))

print(f"{len(excel_files)} datasets found.")

12 datasets found.

In [4]:
for file in excel_files:
    print("="*80)
    print(file.name.upper())
    print("="*80)
    xls=pd.ExcelFile(file)
    print("Sheets:")
    for sheet in xls.sheet_names:
        print("•", sheet)
    print()

================================================================================
ANALYSIS.XLSX
================================================================================
Sheets:
• Analysis

================================================================================
BALANCESHEET.XLSX
================================================================================
Sheets:
• Balance Sheet

================================================================================
CASHFLOW.XLSX
================================================================================
Sheets:
• Cash Flow

================================================================================
COMPANIES.XLSX
================================================================================
Sheets:
• Companies

================================================================================
DOCUMENTS.XLSX
================================================================================
Sheets:
• Documents

================================================================================
FINANCIAL_RATIOS.XLSX
================================================================================
Sheets:
• Sheet1

================================================================================
MARKET_CAP.XLSX
================================================================================
Sheets:
• Sheet1

================================================================================
PEER_GROUPS.XLSX
================================================================================
Sheets:
• Sheet1

================================================================================
PROFITANDLOSS.XLSX
================================================================================
Sheets:
• Profit & Loss

================================================================================
PROSANDCONS.XLSX
================================================================================
Sheets:
• Pros & Cons

================================================================================
SECTORS.XLSX
================================================================================
Sheets:
• Sheet1

================================================================================
STOCK_PRICES.XLSX
================================================================================
Sheets:
• Sheet1

In [5]:
for files in excel_files:
    print("="*80)
    print(file.stem.upper())
    print("="*80)
    df=pd.read_excel(file)
    display(df.head())
    print()
    print(df.info)
    print()
    print(df.describe(include="all"))
    print("\n\n")

================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000



================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000



================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000



================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000



================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000



================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000



================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000



================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000



================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000



================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000



================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000



================================================================================
STOCK_PRICES
================================================================================

,id,company_id,date,open_price,high_price,low_price,close_price,volume,adjusted_close
0,1,ABB,2020-01-01,1958.61,2150.53,1835.28,1964.30,26184368,1964.30
1,2,ABB,2020-02-01,2177.03,2192.92,1931.08,2165.21,1668316,2165.21
2,3,ABB,2020-03-01,2221.26,2440.28,1995.23,2198.78,20578107,2198.78
3,4,ABB,2020-04-01,1932.02,2027.44,1740.12,1958.56,14558597,1958.56
4,5,ABB,2020-05-01,2089.00,2290.96,1878.23,2085.72,44638694,2085.72

<bound method DataFrame.info of         id company_id        date  open_price  high_price  low_price  \
0        1        ABB  2020-01-01     1958.61     2150.53    1835.28
1        2        ABB  2020-02-01     2177.03     2192.92    1931.08
2        3        ABB  2020-03-01     2221.26     2440.28    1995.23
3        4        ABB  2020-04-01     1932.02     2027.44    1740.12
4        5        ABB  2020-05-01     2089.00     2290.96    1878.23
...    ...        ...         ...         ...         ...        ...
5515  5516   TVSMOTOR  2024-08-01     7252.23     7723.71    7009.19
5516  5517   TVSMOTOR  2024-09-01     7204.89     7780.37    6637.12
5517  5518   TVSMOTOR  2024-10-01     7305.20     7955.73    7189.07
5518  5519   TVSMOTOR  2024-11-01     7080.04     7361.93    6539.05
5519  5520   TVSMOTOR  2024-12-01     7774.57     7993.90    7114.42

      close_price    volume  adjusted_close
0         1964.30  26184368         1964.30
1         2165.21   1668316         2165.21
2         2198.78  20578107         2198.78
3         1958.56  14558597         1958.56
4         2085.72  44638694         2085.72
...           ...       ...             ...
5515      7205.77  38060354         7205.77
5516      7220.89   5976332         7220.89
5517      7292.74  18767834         7292.74
5518      7177.83  44966229         7177.83
5519      7640.79  42370949         7640.79

[5520 rows x 9 columns]>

                 id company_id        date    open_price    high_price  \
count   5520.000000       5520        5520   5520.000000   5520.000000
unique          NaN         92          60           NaN           NaN
top             NaN        ABB  2020-01-01           NaN           NaN
freq            NaN         60          92           NaN           NaN
mean    2760.500000        NaN         NaN   3197.062589   3405.899678
std     1593.631074        NaN         NaN   2311.462218   2467.807070
min        1.000000        NaN         NaN     86.190000     87.270000
25%     1380.750000        NaN         NaN   1351.977500   1432.917500
50%     2760.500000        NaN         NaN   2743.090000   2918.985000
75%     4140.250000        NaN         NaN   4671.767500   4973.935000
max     5520.000000        NaN         NaN  15760.700000  16599.390000

           low_price   close_price        volume  adjusted_close
count    5520.000000   5520.000000  5.520000e+03     5520.000000
unique           NaN           NaN           NaN             NaN
top              NaN           NaN           NaN             NaN
freq             NaN           NaN           NaN             NaN
mean     2989.256685   3196.612759  2.532394e+07     3196.612759
std      2166.850558   2309.560919  1.428282e+07     2309.560919
min        79.380000     85.010000  1.067210e+05       85.010000
25%      1253.040000   1349.560000  1.300554e+07     1349.560000
50%      2568.110000   2748.845000  2.575014e+07     2748.845000
75%      4370.395000   4682.132500  3.743892e+07     4682.132500
max     14302.310000  15507.440000  4.999625e+07    15507.440000

In [6]:
profile = []

for file in excel_files:

    df = pd.read_excel(file)

    profile.append({

        "Dataset": file.stem,

        "Rows": len(df),

        "Columns": len(df.columns),

        "Missing": df.isna().sum().sum(),

        "Duplicates": df.duplicated().sum(),

        "Memory (KB)": round(df.memory_usage(deep=True).sum()/1024,2)

    })

profile = pd.DataFrame(profile)

display(profile)

             Dataset  Rows  Columns  Missing  Duplicates  Memory (KB)
0           analysis    21        6        0           0         2.95
1       balancesheet  1313       13        0           0       547.59
2           cashflow  1188        7        8           0       244.98
3          companies    93       12        9           0        70.46
4          documents  1586        4       52           0       235.10
5   financial_ratios  1184       16      170           0       165.51
6         market_cap   552        9        0           0        42.71
7        peer_groups    56        4        0           0         2.54
8      profitandloss  1277       15      231           0       621.37
9        prosandcons    17        4        6           0         2.58
10           sectors    92        6        0           0         8.30
11      stock_prices  5520        9        0           0       479.89

In [7]:
profile.to_csv(

    PROJECT_ROOT /
    "data" /
    "output" /
    "dataset_profile.csv",

    index=False

)

print("Dataset profile saved.")

Dataset profile saved.