In [1]:
import sqlite3
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

DB_PATH = PROJECT_ROOT / "data" / "nifty100.db"

conn = sqlite3.connect(DB_PATH)

In [2]:
tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name;
""", conn)

tables

                name
0           analysis
1       balancesheet
2           cashflow
3          companies
4          documents
5   financial_ratios
6         market_cap
7        peer_groups
8      profitandloss
9        prosandcons
10           sectors
11      stock_prices

In [3]:
tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name;
""", conn)

tables

                name
0           analysis
1       balancesheet
2           cashflow
3          companies
4          documents
5   financial_ratios
6         market_cap
7        peer_groups
8      profitandloss
9        prosandcons
10           sectors
11      stock_prices

In [4]:
pd.read_sql(
    "PRAGMA foreign_key_check;",
    conn
)

Empty DataFrame
Columns: [table, rowid, parent, fkid]
Index: []

In [5]:
conn.close()