In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

In [3]:
import importlib
import pandas as pd

import src.screener.engine as engine

importlib.reload(engine)

In [7]:
import importlib
import src.screener.engine as engine

importlib.reload(engine)

quality = engine.run_screener(
    "quality_compounder",
    DB_PATH
)

print(quality.columns.tolist())

['company_id', 'company_name', 'year', 'broad_sector', 'return_on_equity_pct', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'dividend_payout_ratio_pct', 'market_cap_crore', 'pe_ratio', 'pb_ratio', 'dividend_yield_pct', 'sales', 'net_profit', 'compounded_sales_growth', 'compounded_profit_growth', 'return_on_equity_pct_score', 'net_profit_margin_pct_score', 'compounded_sales_growth_score', 'free_cash_flow_cr_score', 'debt_to_equity_score', 'composite_score']

In [4]:
DB_PATH = r"C:\Nifty100_Data_Foundation\data\nifty100.db"

In [5]:
quality = engine.run_screener(
    "quality_compounder",
    DB_PATH
)

In [6]:
quality[
    [
        "company_name",
        "broad_sector",
        "composite_score",
        "sector_rank",
        "sector_percentile",
        "overall_rank"
    ]
]

KeyError: "['sector_rank', 'sector_percentile', 'overall_rank'] not in index"

In [8]:
import src.screener.engine as engine

print(engine.calculate_sector_percentile)

<function calculate_sector_percentile at 0x0000019B193E6660>

In [9]:
df = engine.load_screener_data(DB_PATH)

In [10]:
df = engine.calculate_composite_score(df)

In [11]:
df.columns.tolist()

['company_id',
 'company_name',
 'year',
 'broad_sector',
 'return_on_equity_pct',
 'net_profit_margin_pct',
 'operating_profit_margin_pct',
 'debt_to_equity',
 'interest_coverage',
 'asset_turnover',
 'free_cash_flow_cr',
 'dividend_payout_ratio_pct',
 'market_cap_crore',
 'pe_ratio',
 'pb_ratio',
 'dividend_yield_pct',
 'sales',
 'net_profit',
 'compounded_sales_growth',
 'compounded_profit_growth',
 'return_on_equity_pct_score',
 'net_profit_margin_pct_score',
 'compounded_sales_growth_score',
 'free_cash_flow_cr_score',
 'debt_to_equity_score',
 'composite_score']

In [12]:
df = engine.calculate_sector_percentile(df)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [13]:
print(df["broad_sector"].isna().sum())
print(df["composite_score"].isna().sum())

0
86

In [14]:
df = engine.load_screener_data(DB_PATH)

print(df.shape)

(90, 20)

In [15]:
df = engine.calculate_composite_score(df)

print(df["composite_score"].isna().sum())

86

In [16]:
df[df["composite_score"].isna()][
    [
        "company_name",
        "return_on_equity_pct",
        "net_profit_margin_pct",
        "compounded_sales_growth",
        "free_cash_flow_cr",
        "debt_to_equity",
        "composite_score",
    ]
]

,company_name,return_on_equity_pct,net_profit_margin_pct,compounded_sales_growth,free_cash_flow_cr,debt_to_equity,composite_score
0,Abbott India Ltd,32.468235,20.533425,NaN,797.0,0.022438,NaN
1,Adani Energy Solutions Ltd,9.461277,7.201782,NaN,1095.0,2.932521,NaN
2,Adani Enterprises Ltd,8.534650,3.458790,NaN,-8455.0,1.671358,NaN
3,Adani Green Energy Ltd,12.812691,13.665944,NaN,-13347.0,6.595282,NaN
4,Adani Ports & Special Economic Zone Ltd\n,15.354883,30.339560,NaN,8250.0,0.937322,NaN
...,...,...,...,...,...,...,...
85,Tech Mahindra Ltd,8.987964,4.609970,NaN,5058.0,0.095129,NaN
86,Titan Company Ltd\n,37.219206,6.843630,NaN,1506.0,1.653146,NaN
87,Torrent Pharmaceuticals Ltd,24.154026,15.436242,NaN,3106.0,0.586639,NaN
88,Trent Ltd,36.307768,11.935354,NaN,841.0,0.430924,NaN
89,TVS Motor Company Ltd,26.223467,4.544642,NaN,-2254.0,3.833432,NaN

In [17]:
print(df.dtypes)

company_id                           str
company_name                         str
year                             float64
broad_sector                         str
return_on_equity_pct             float64
net_profit_margin_pct            float64
operating_profit_margin_pct      float64
debt_to_equity                   float64
interest_coverage                float64
asset_turnover                   float64
free_cash_flow_cr                float64
dividend_payout_ratio_pct        float64
market_cap_crore                 float64
pe_ratio                         float64
pb_ratio                         float64
dividend_yield_pct               float64
sales                            float64
net_profit                       float64
compounded_sales_growth          float64
compounded_profit_growth         float64
return_on_equity_pct_score       float64
net_profit_margin_pct_score      float64
compounded_sales_growth_score    float64
free_cash_flow_cr_score          float64
debt_to_equity_score             float64
composite_score                  float64
dtype: object

In [18]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(DB_PATH)

pd.read_sql("""
SELECT company_id,
       compounded_sales_growth
FROM analysis
LIMIT 20
""", conn)

   company_id          compounded_sales_growth
0    HDFCBANK                    10 Years: 21%
1    HDFCBANK               5 Years:       22%
2    HDFCBANK               3 Years:       30%
3    HDFCBANK              TTM:            47%
4        INFY                10 Years:     12%
5        INFY               5 Years:       13%
6        INFY                3 Years:       5%
7        INFY               TTM:            3%
8     SBILIFE                10 Years:     23%
9     SBILIFE               5 Years:       24%
10    SBILIFE               3 Years:       17%
11    SBILIFE              TTM:            43%
12        TCS   10 Years:     11%
13        TCS  5 Years:       10%
14        TCS  3 Years:       14%
15        TCS  TTM:            5%

In [19]:
conn = sqlite3.connect(DB_PATH)

pd.read_sql("""
SELECT COUNT(DISTINCT company_id) AS companies
FROM analysis;
""", conn)

   companies
0          4

In [20]:
pd.read_sql("""
SELECT COUNT(*) AS rows
FROM analysis;
""", conn)

   rows
0    16

In [21]:
import pandas as pd

pd.read_sql("""
SELECT COUNT(DISTINCT company_id)
FROM financial_ratios
WHERE revenue_cagr_5yr IS NOT NULL;
""", conn)

DatabaseError: Execution failed on sql '
SELECT COUNT(DISTINCT company_id)
FROM financial_ratios
WHERE revenue_cagr_5yr IS NOT NULL;
': no such column: revenue_cagr_5yr

In [22]:
pd.read_sql("""
PRAGMA table_info(financial_ratios);
""", conn)

    cid                         name     type  notnull dflt_value  pk
0     0                   company_id     TEXT        0       None   0
1     1                         year     REAL        0       None   0
2     2        net_profit_margin_pct     REAL        0       None   0
3     3  operating_profit_margin_pct     REAL        0       None   0
4     4         return_on_equity_pct     REAL        0       None   0
5     5         return_on_assets_pct     REAL        0       None   0
6     6               debt_to_equity     REAL        0       None   0
7     7            interest_coverage     REAL        0       None   0
8     8               asset_turnover     REAL        0       None   0
9     9            free_cash_flow_cr     REAL        0       None   0
10   10                     capex_cr     REAL        0       None   0
11   11           earnings_per_share     REAL        0       None   0
12   12         book_value_per_share     REAL        0       None   0
13   13    dividend_payout_ratio_pct     REAL        0       None   0
14   14                total_debt_cr     REAL        0       None   0
15   15      cash_from_operations_cr     REAL        0       None   0
16   16      composite_quality_score  INTEGER        0       None   0

In [23]:
df = pd.read_sql("""
SELECT *
FROM financial_ratios
LIMIT 1;
""", conn)

print(df.columns.tolist())

['company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'return_on_assets_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr', 'composite_quality_score']

In [24]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

                name
0          companies
1      profitandloss
2       balancesheet
3           cashflow
4           analysis
5          documents
6         market_cap
7        peer_groups
8        prosandcons
9            sectors
10      stock_prices
11  financial_ratios

In [25]:
pd.read_sql("""
PRAGMA table_info(analysis);
""", conn)

   cid                      name     type  notnull dflt_value  pk
0    0                        id  INTEGER        0       None   1
1    1                company_id     TEXT        1       None   0
2    2   compounded_sales_growth     TEXT        0       None   0
3    3  compounded_profit_growth     TEXT        0       None   0
4    4          stock_price_cagr     TEXT        0       None   0
5    5                       roe     TEXT        0       None   0