In [1]:
print("Profit duplicates:")
print(
    profit.groupby(["company_id", "year"])
    .size()
    .reset_index(name="count")
    .query("count > 1")
    .head(20)
)

print("\nBalance duplicates:")
print(
    balance.groupby(["company_id", "year"])
    .size()
    .reset_index(name="count")
    .query("count > 1")
    .head(20)
)

print("\nCashflow duplicates:")
print(
    cash.groupby(["company_id", "year"])
    .size()
    .reset_index(name="count")
    .query("count > 1")
    .head(20)
)

Profit duplicates:

NameError: name 'profit' is not defined

In [4]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)

c:\Nifty100_Data_Foundation

In [5]:
from src.screener.engine import load_config

config = load_config()
print(config)

None

In [5]:
from src.screener.engine import CONFIG

print("CONFIG PATH:", CONFIG)
print("EXISTS:", CONFIG.exists())

CONFIG PATH: C:\Nifty100_Data_Foundation\config\screener_config.yaml
EXISTS: True

In [6]:
from src.screener.engine import CONFIG

print(CONFIG)
print(CONFIG.exists())

C:\Nifty100_Data_Foundation\config\screener_config.yaml
True

In [7]:
import yaml
from src.screener.engine import CONFIG

with open(CONFIG, "r") as f:
    data = yaml.safe_load(f)

print(data)
print(type(data))

{'quality_compounder': {'roe_min': 15, 'debt_to_equity_max': 1, 'free_cash_flow_min': 0, 'revenue_cagr_5yr_min': 10}, 'value_pick': {'pe_max': 20, 'pb_max': 3, 'debt_to_equity_max': 2, 'dividend_yield_min': 1}, 'growth_accelerator': {'pat_cagr_5yr_min': 20, 'revenue_cagr_5yr_min': 15, 'debt_to_equity_max': 2}, 'dividend_champion': {'dividend_yield_min': 2, 'dividend_payout_max': 80, 'free_cash_flow_min': 0}, 'debt_free_bluechip': {'debt_to_equity_max': 0, 'roe_min': 12, 'sales_min': 5000}, 'turnaround_watch': {'revenue_cagr_3yr_min': 10}}
<class 'dict'>

In [8]:
from src.screener.engine import load_config, CONFIG

print("CONFIG PATH:", CONFIG)
print("EXISTS:", CONFIG.exists())

config = load_config()

print("CONFIG DATA:", config)
print("TYPE:", type(config))

CONFIG PATH: C:\Nifty100_Data_Foundation\config\screener_config.yaml
EXISTS: True
CONFIG DATA: {'quality_compounder': {'roe_min': 15, 'debt_to_equity_max': 1, 'free_cash_flow_min': 0, 'revenue_cagr_5yr_min': 10}, 'value_pick': {'pe_max': 20, 'pb_max': 3, 'debt_to_equity_max': 2, 'dividend_yield_min': 1}, 'growth_accelerator': {'pat_cagr_5yr_min': 20, 'revenue_cagr_5yr_min': 15, 'debt_to_equity_max': 2}, 'dividend_champion': {'dividend_yield_min': 2, 'dividend_payout_max': 80, 'free_cash_flow_min': 0}, 'debt_free_bluechip': {'debt_to_equity_max': 0, 'roe_min': 12, 'sales_min': 5000}, 'turnaround_watch': {'revenue_cagr_3yr_min': 10}}
TYPE: <class 'dict'>

In [7]:
print(CONFIG.read_text())

In [9]:
import sqlite3
import pandas as pd
from pathlib import Path

DB_PATH = Path("..") / "data" / "nifty100.db"

conn = sqlite3.connect(DB_PATH)

query = "SELECT * FROM financial_ratios LIMIT 5"

df = pd.read_sql(query, conn)

print(df.columns.tolist())

['company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'return_on_assets_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr', 'composite_quality_score']

In [10]:
import sqlite3
import pandas as pd
from pathlib import Path

DB_PATH = Path("..") / "data" / "nifty100.db"

conn = sqlite3.connect(DB_PATH)

tables = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

print(tables)

                name
0          companies
1      profitandloss
2       balancesheet
3           cashflow
4           analysis
5          documents
6         market_cap
7        peer_groups
8        prosandcons
9            sectors
10      stock_prices
11  financial_ratios

In [11]:
for table in tables["name"]:
    cols = pd.read_sql(f"PRAGMA table_info({table});", conn)
    print(f"\n=== {table} ===")
    print(cols["name"].tolist())

=== companies ===
['company_id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']

=== profitandloss ===
['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout']

=== balancesheet ===
['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets']

=== cashflow ===
['id', 'company_id', 'year', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow']

=== analysis ===
['id', 'company_id', 'compounded_sales_growth', 'compounded_profit_growth', 'stock_price_cagr', 'roe']

=== documents ===
['id', 'company_id', 'year', 'annual_report']

=== market_cap ===
['id', 'company_id', 'year', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct']

=== peer_groups ===
['id', 'peer_group_name', 'company_id', 'is_benchmark']

=== prosandcons ===
['id', 'company_id', 'pros', 'cons']

=== sectors ===
['id', 'company_id', 'broad_sector', 'sub_sector', 'index_weight_pct', 'market_cap_category']

=== stock_prices ===
['id', 'company_id', 'date', 'open_price', 'high_price', 'low_price', 'close_price', 'volume', 'adjusted_close']

=== financial_ratios ===
['company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'return_on_assets_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr', 'composite_quality_score']

In [12]:
sector_cols = pd.read_sql("PRAGMA table_info(sectors);", conn)
print(sector_cols["name"].tolist())

['id', 'company_id', 'broad_sector', 'sub_sector', 'index_weight_pct', 'market_cap_category']

In [18]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

In [20]:
from src.screener.engine import load_screener_data, apply_filters

ImportError: cannot import name 'load_screener_data' from 'src.screener.engine' (c:\Nifty100_Data_Foundation\src\screener\engine.py)

In [19]:
DB_PATH = PROJECT_ROOT / "data" / "nifty100.db"

df = load_screener_data(DB_PATH)

print(df.shape)
df.head()

NameError: name 'load_screener_data' is not defined

In [21]:
import importlib
import src.screener.engine as engine

importlib.reload(engine)

In [22]:
df = engine.load_screener_data(DB_PATH)

print(df.shape)

(1200, 20)

In [23]:
from src.screener.engine import load_screener_data, apply_filters

In [25]:
print(df.dtypes)

company_id                         str
company_name                       str
year                           float64
broad_sector                       str
return_on_equity_pct           float64
net_profit_margin_pct          float64
operating_profit_margin_pct    float64
debt_to_equity                 float64
interest_coverage              float64
asset_turnover                 float64
free_cash_flow_cr              float64
dividend_payout_ratio_pct      float64
market_cap_crore               float64
pe_ratio                       float64
pb_ratio                       float64
dividend_yield_pct             float64
sales                          float64
net_profit                     float64
compounded_sales_growth            str
compounded_profit_growth           str
dtype: object

In [26]:
for col in df.columns:
    print(f"{col:<35} {df[col].dtype}")

company_id                          str
company_name                        str
year                                float64
broad_sector                        str
return_on_equity_pct                float64
net_profit_margin_pct               float64
operating_profit_margin_pct         float64
debt_to_equity                      float64
interest_coverage                   float64
asset_turnover                      float64
free_cash_flow_cr                   float64
dividend_payout_ratio_pct           float64
market_cap_crore                    float64
pe_ratio                            float64
pb_ratio                            float64
dividend_yield_pct                  float64
sales                               float64
net_profit                          float64
compounded_sales_growth             str
compounded_profit_growth            str

In [24]:
quality = engine.apply_filters(df, "quality_compounder")

TypeError: Invalid comparison between dtype=str and int

In [27]:
import importlib
import src.screener.engine as engine

importlib.reload(engine)

In [28]:
df = engine.load_screener_data(DB_PATH)

print(df.dtypes)

company_id                         str
company_name                       str
year                           float64
broad_sector                       str
return_on_equity_pct           float64
net_profit_margin_pct          float64
operating_profit_margin_pct    float64
debt_to_equity                 float64
interest_coverage              float64
asset_turnover                 float64
free_cash_flow_cr              float64
dividend_payout_ratio_pct      float64
market_cap_crore               float64
pe_ratio                       float64
pb_ratio                       float64
dividend_yield_pct             float64
sales                          float64
net_profit                     float64
compounded_sales_growth        float64
compounded_profit_growth       float64
dtype: object

In [29]:
quality = engine.apply_filters(df, "quality_compounder")

print(quality.shape)
quality.head()

(0, 20)

Empty DataFrame
Columns: [company_id, company_name, year, broad_sector, return_on_equity_pct, net_profit_margin_pct, operating_profit_margin_pct, debt_to_equity, interest_coverage, asset_turnover, free_cash_flow_cr, dividend_payout_ratio_pct, market_cap_crore, pe_ratio, pb_ratio, dividend_yield_pct, sales, net_profit, compounded_sales_growth, compounded_profit_growth]
Index: []

In [30]:
print("ROE >= 15:", (df["return_on_equity_pct"] >= 15).sum())

print("D/E <= 1:", (df["debt_to_equity"] <= 1).sum())

print("FCF >= 0:", (df["free_cash_flow_cr"] >= 0).sum())

print("Sales CAGR >= 10:", (df["compounded_sales_growth"] >= 10).sum())

ROE >= 15: 713
D/E <= 1: 752
FCF >= 0: 823
Sales CAGR >= 10: 0

In [31]:
print(df["compounded_sales_growth"].head(20))
print(df["compounded_sales_growth"].describe())
print(df["compounded_sales_growth"].isna().sum())

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
Name: compounded_sales_growth, dtype: float64
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: compounded_sales_growth, dtype: float64
1200

In [32]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(DB_PATH)

pd.read_sql("""
SELECT company_id,
       compounded_sales_growth,
       compounded_profit_growth
FROM analysis
LIMIT 20
""", conn)

   company_id          compounded_sales_growth  compounded_profit_growth
0    HDFCBANK                    10 Years: 21%             10 Years: 22%
1    HDFCBANK               5 Years:       22%    5 Years:           23%
2    HDFCBANK               3 Years:       30%    3 Years:           26%
3    HDFCBANK              TTM:            47%   TTM:                27%
4        INFY                10 Years:     12%      10 Years:         9%
5        INFY               5 Years:       13%    5 Years:           11%
6        INFY                3 Years:       5%    3 Years:           10%
7        INFY               TTM:            3%   TTM:                 8%
8     SBILIFE                10 Years:     23%     10 Years:          9%
9     SBILIFE               5 Years:       24%    5 Years:            6%
10    SBILIFE               3 Years:       17%    3 Years:            9%
11    SBILIFE              TTM:            43%  TTM:                 18%
12        TCS   10 Years:     11%                  10 Years:          9%
13        TCS  5 Years:       10%                 5 Years:            8%
14        TCS  3 Years:       14%                3 Years:            12%
15        TCS  TTM:            5%                TTM:                 8%

In [33]:
import importlib
import src.screener.engine as engine

importlib.reload(engine)

df = engine.load_screener_data(DB_PATH)

print(df["compounded_sales_growth"].head())

quality = engine.apply_filters(df, "quality_compounder")

print(quality.shape)

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: compounded_sales_growth, dtype: float64
(32, 20)

In [34]:
df[df["compounded_sales_growth"].notna()][
    ["company_name", "compounded_sales_growth"]
].head(10)

      company_name  compounded_sales_growth
445  HDFC Bank Ltd                     22.0
446  HDFC Bank Ltd                     22.0
447  HDFC Bank Ltd                     22.0
448  HDFC Bank Ltd                     22.0
449  HDFC Bank Ltd                     22.0
450  HDFC Bank Ltd                     22.0
451  HDFC Bank Ltd                     22.0
452  HDFC Bank Ltd                     22.0
453  HDFC Bank Ltd                     22.0
454  HDFC Bank Ltd                     22.0

In [35]:
import importlib
import src.screener.engine as engine

importlib.reload(engine)

df = engine.load_screener_data(DB_PATH)

print(df.shape)

quality = engine.apply_filters(df, "quality_compounder")

print(quality.shape)

(90, 20)
(2, 20)

In [4]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

In [5]:
import importlib
import src.screener.engine as engine

importlib.reload(engine)

In [19]:
DB_PATH = r"C:/Nifty100_Data_Foundation/data/nifty100.db"

In [20]:
print(DB_PATH)

C:/Nifty100_Data_Foundation/data/nifty100.db

In [21]:
import importlib
import src.screener.engine as engine

importlib.reload(engine)

print(hasattr(engine, "run_screener"))

True

In [22]:
dir(engine)

['CONFIG',
 'FILTER_MAP',
 'Path',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'apply_filters',
 'load_config',
 'load_screener_data',
 'pd',
 'run_screener',
 'sqlite3',
 'yaml']

In [23]:
presets = [
    "quality_compounder",
    "value_pick",
    "growth_accelerator",
    "dividend_champion",
    "debt_free_bluechip",
    "turnaround_watch"
]

for preset in presets:
    result = engine.run_screener(preset, DB_PATH)
    print(f"{preset:25} {len(result)} companies")

quality_compounder        2 companies
value_pick                2 companies
growth_accelerator        1 companies
dividend_champion         31 companies
debt_free_bluechip        18 companies
turnaround_watch          90 companies

In [15]:
import importlib
import src.screener.engine as engine

importlib.reload(engine)

In [16]:
presets = [
    "quality_compounder",
    "value_pick",
    "growth_accelerator",
    "dividend_champion",
    "debt_free_bluechip",
    "turnaround_watch"
]

for preset in presets:
    result = engine.run_screener(preset, DB_PATH)
    print(f"{preset:25} {len(result)} companies")

OperationalError: unable to open database file

In [17]:
print(DB_PATH)

path/to/your/nifty100.db

In [18]:
from pathlib import Path

for file in Path(r"C:\Nifty100_Data_Foundation").rglob("*.db"):
    print(file)

C:\Nifty100_Data_Foundation\data\nifty100.db

In [25]:
print(hasattr(engine, "calculate_composite_score"))

False

In [24]:
quality = engine.run_screener(
    "quality_compounder",
    DB_PATH
)

quality[
    [
        "company_name",
        "return_on_equity_pct",
        "debt_to_equity",
        "compounded_sales_growth",
        "composite_score",
    ]
].head()

KeyError: "['composite_score'] not in index"

In [41]:
import importlib
import src.screener.engine as engine

importlib.reload(engine)

In [42]:
quality = engine.run_screener(
    "quality_compounder",
    DB_PATH
)

print(quality.columns.tolist())

['company_id', 'company_name', 'year', 'broad_sector', 'return_on_equity_pct', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'dividend_payout_ratio_pct', 'market_cap_crore', 'pe_ratio', 'pb_ratio', 'dividend_yield_pct', 'sales', 'net_profit', 'compounded_sales_growth', 'compounded_profit_growth', 'return_on_equity_pct_score', 'net_profit_margin_pct_score', 'compounded_sales_growth_score', 'free_cash_flow_cr_score', 'debt_to_equity_score', 'composite_score']

In [44]:
quality = engine.run_screener(
    "quality_compounder",
    DB_PATH
)

quality[
    [
        "company_name",
        "return_on_equity_pct_score",
        "net_profit_margin_pct_score",
        "compounded_sales_growth_score",
        "free_cash_flow_cr_score",
        "debt_to_equity_score",
        "composite_score",
    ]
]

,company_name,return_on_equity_pct_score,net_profit_margin_pct_score,compounded_sales_growth_score,free_cash_flow_cr_score,debt_to_equity_score,composite_score
0,Tata Consultancy Services Ltd,92.222222,68.888889,25.0,100.000000,66.666667,71.833333
1,Infosys Ltd,81.111111,65.555556,50.0,88.888889,65.555556,71.000000

In [36]:
df = engine.load_screener_data(DB_PATH)

df = engine.calculate_composite_score(df)

In [37]:
print(df["return_on_equity_pct"].describe())

print(df["net_profit_margin_pct"].describe())

count      90.000000
mean      125.066462
std       640.616051
min        -5.334927
25%        11.612115
50%        16.274382
75%        26.083288
max      4744.047619
Name: return_on_equity_pct, dtype: float64
count     90.000000
mean      20.118918
std       45.682288
min       -3.979852
25%        7.217103
50%       14.118130
75%       20.379774
max      432.726204
Name: net_profit_margin_pct, dtype: float64

In [38]:
df[
    ["company_name", "return_on_equity_pct"]
].sort_values(
    by="return_on_equity_pct",
    ascending=False
).head(10)

                           company_name  return_on_equity_pct
15               Bharat Electronics Ltd           4744.047619
34            Hindustan Aeronautics Ltd           3816.582915
45              Interglobe Aviation Ltd            892.568306
65                     Nestle India Ltd            117.754491
59                  Larsen & Toubro Ltd             77.665101
71                 Punjab National Bank             61.320565
20             Britannia Industries Ltd             54.148693
84        Tata Consultancy Services Ltd             50.944314
57  Life Insurance Corporation of India             49.447110
5                       Adani Power Ltd             48.276741

In [39]:
df[
    ["company_name", "net_profit_margin_pct"]
].sort_values(
    by="net_profit_margin_pct",
    ascending=False
).head(10)

                                 company_name  net_profit_margin_pct
12            Bajaj Holdings & Investment Ltd             432.726204
53                 Jio Financial Services Ltd              86.522911
27                                    DLF Ltd              42.383694
66                                 NHPC Ltd\n              41.818937
5                             Adani Power Ltd              41.367599
72        Power Grid Corporation of India Ltd              33.970290
56                  Kotak Mahindra Bank Ltd\n              32.386151
4   Adani Ports & Special Economic Zone Ltd\n              30.339560
73                                    REC Ltd              29.768293
51                                  ITC Ltd\n              29.282025

In [40]:
quality[
    [
        "company_name",
        "return_on_equity_pct_score",
        "net_profit_margin_pct_score",
        "compounded_sales_growth_score",
        "free_cash_flow_cr_score",
        "debt_to_equity_score",
        "composite_score"
    ]
]

,company_name,return_on_equity_pct_score,net_profit_margin_pct_score,compounded_sales_growth_score,free_cash_flow_cr_score,debt_to_equity_score,composite_score
0,Tata Consultancy Services Ltd,70.711190,48.286559,0.000000,100.000000,98.855480,62.163431
1,Infosys Ltd,38.714331,42.661761,19.245283,76.123537,98.773967,52.100794

In [46]:
import pandas as pd

In [48]:
import sqlite3
import pandas as pd

conn = sqlite3.connect( r"C:/Nifty100_Data_Foundation/data/nifty100.db")

In [49]:
pd.read_sql("""
SELECT *
FROM analysis;
""", conn)

,id,company_id,compounded_sales_growth,compounded_profit_growth,stock_price_cagr,roe
0,1,HDFCBANK,10 Years: 21%,10 Years: 22%,10 Years: 15%,10 Years: 17%
1,2,HDFCBANK,5 Years: 22%,5 Years: 23%,5 Years: 8%,5 Years: 17%
2,3,HDFCBANK,3 Years: 30%,3 Years: 26%,3 Years: 8%,3 Years: 17%
3,4,HDFCBANK,TTM: 47%,TTM: 27%,1 Year: 13%,Last Year: 17%
4,5,INFY,10 Years: 12%,10 Years: 9%,10 Years: 15%,10 Years: 27%
5,6,INFY,5 Years: 13%,5 Years: 11%,5 Years: 22%,5 Years: 29%
6,7,INFY,3 Years: 5%,3 Years: 10%,3 Years: 4%,3 Years: 31%
7,8,INFY,TTM: 3%,TTM: 8%,1 Year: 27%,Last Year: 32%
8,9,SBILIFE,10 Years: 23%,10 Years: 9%,10 Years: 9%,10 Years: 16%
9,10,SBILIFE,5 Years: 24%,5 Years: 6%,5 Years: 8%,5 Years 14%
10,11,SBILIFE,3 Years: 17%,3 Years: 9%,3 Years: 7%,3 Years: 13%
11,12,SBILIFE,TTM: 43%,TTM: 18%,1 Year: -2%,Last Year: 12%
12,13,TCS,10 Years: 11%,10 Years: 9%,10 Years: 14%,10 Years: 40%
13,14,TCS,5 Years: 10%,5 Years: 8%,5 Years: 16%,5 Years: 44%
14,15,TCS,3 Years: 14%,3 Years: 12%,3 Years: 8%,3 Years: 47%
15,16,TCS,TTM: 5%,TTM: 8%,1 Year: 16%,Last Year: 52%

In [50]:
pd.read_sql("""
SELECT COUNT(*)
FROM analysis;
""", conn)

   COUNT(*)
0        16

In [53]:
import pandas as pd

analysis_df = pd.read_csv(r"C:\Nifty100_Data_Foundation\data\processed\analysis.csv")   # or read_excel(...)
print(analysis_df.shape)
print(analysis_df["company_id"].nunique())

(20, 6)
5

In [51]:
xls = pd.ExcelFile("your_source_file.xlsx")
print(xls.sheet_names)

FileNotFoundError: [Errno 2] No such file or directory: 'your_source_file.xlsx'